name: remote ssh command
on: [push]
jobs:

  ssh:
    name: ssh
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: {%- raw -%} ${{ secrets.SSH_PRIVATE_KEY }} {% endraw %}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
