name: remote ssh command
on: [push]
jobs:

  ssh:
    name: ssh
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: List All Files
        run: |
          pwd
          ls -altr
          "Test Text file" > test.txt
        
      - name: Deploy with rsync
        run: rsync -avz ./test.txt ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:'C:\inetpub\wwwroot\mywebsite'
