name: SSH
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  build:
    name: SSH
    runs-on: windows-latest
    steps:
      - name: SSH
        run: |
         ssh tamilcloud1003@34.132.65.36
