name: winrm
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  build:
    name: winrm
    runs-on: windows-latest
    steps:
      - name: winrm
        shell: powershell
        run: |
          Set-Item wsman:\localhost\Client\TrustedHosts ${{ secrets.WINRM_HOST }} -Concatenate -Force
          $WinRMPassword = ConvertTo-SecureString "${{ secrets.WINRM_PASSWORD }}" -AsPlainText -Force
          $WinRMCredential = New-Object System.Management.Automation.PSCredential ( "${{ secrets.WINRM_USERNAME }}" , $WinRMPassword)
          Enter-PSSession -ComputerName ${{ secrets.WINRM_HOST }} -Credential $WinRMCredential
          Invoke-Command -ComputerName ${{ secrets.WINRM_HOST }} -ScriptBlock { cd c:\inetpub\wwwroot\mywebsite\; dir; type HEY_I_AM_HERE.txt} -credential $WinRMCredential
