name: winrm
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  build:
    name: winrm
    runs-on: windows-latest
    steps:
      - name: winrm
        shell: powershell
        run: |
          Set-Item wsman:\localhost\Client\TrustedHosts ${{ secrets.WINRM_HOST }} -Concatenate -Force
          $WinRMPassword = ConvertTo-SecureString "${{ secrets.WINRM_PASSWORD }}" -AsPlainText -Force
          $WinRMCredential = New-Object System.Management.Automation.PSCredential ( "${{ secrets.WINRM_USERNAME }}" , $WinRMPassword)
          Enter-PSSession -ComputerName ${{ secrets.WINRM_HOST }} -Credential $WinRMCredential
          dir
          
          #Get-Item WSMan:\localhost\Client\TrustedHosts                 
          #Set-Item WSMan:\localhost\Client\TrustedHosts -Value ${{ secrets.WINRM_HOST }}
          #systeminfo
          #Get-Host | Select-Object Version
          #whoami
          #winrm quickconfig
          #Get-Item WSMan:\localhost\Client\TrustedHosts
          #Set-Item WSMan:\localhost\Client\TrustedHosts -Value *
