name: winrm
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  build:
    name: winrm
    runs-on: windows-latest
    steps:
      - name: winrm
        shell: powershell
        run: |
          Set-Item wsman:\localhost\Client\TrustedHosts ${{ secrets.WINRM_HOST }} -Concatenate -Force
          Get-Item WSMan:\localhost\Client\TrustedHosts        
          
          #Set-Item WSMan:\localhost\Client\TrustedHosts -Value ${{ secrets.WINRM_HOST }}
          #systeminfo
          #Get-Host | Select-Object Version
          #whoami
          #winrm quickconfig
          #Get-Item WSMan:\localhost\Client\TrustedHosts
          #Set-Item WSMan:\localhost\Client\TrustedHosts -Value *
