name: winrm
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  build:
    name: winrm
    runs-on: windows-latest
    steps:
      - name: winrm
        shell: powershell
        run: |
          systeminfo
          Get-Host | Select-Object Version
          whoami
          #winrm quickconfig
          #Get-Item WSMan:\localhost\Client\TrustedHosts
          #Set-Item WSMan:\localhost\Client\TrustedHosts -Value *
          Set-Item wsman:\localhost\Client\TrustedHosts 34.132.65.36 -Concatenate -Force
          #Set-Item WSMan:\localhost\Client\TrustedHosts -Value ${{ secrets.WINRM_HOST }}
