name: winrm
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  build:
    name: winrm
    runs-on: windows-latest
    steps:
      - name: winrm
        shell: powershell
        run: |
          Get-Host | Select-Object Version
          #winrm quickconfig
          Get-Item WSMan:\localhost\Client\TrustedHosts
          Set-Item WSMan:\localhost\Client\TrustedHosts -Value "34.132.65.36"
          #Set-Item WSMan:\localhost\Client\TrustedHosts -Value ${{ secrets.WINRM_HOST }}
